// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.ufpb.dsc.mma.domain;

import br.com.ufpb.dsc.mma.domain.Category;
import br.com.ufpb.dsc.mma.domain.CategoryDataOnDemand;
import br.com.ufpb.dsc.mma.persistence.CategoryRepository;
import br.com.ufpb.dsc.mma.service.CategoryService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CategoryDataOnDemand: @Component;
    
    private Random CategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<Category> CategoryDataOnDemand.data;
    
    @Autowired
    CategoryService CategoryDataOnDemand.categoryService;
    
    @Autowired
    CategoryRepository CategoryDataOnDemand.categoryRepository;
    
    public Category CategoryDataOnDemand.getNewTransientCategory(int index) {
        Category obj = new Category();
        setMaxWeight(obj, index);
        setMinWeight(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void CategoryDataOnDemand.setMaxWeight(Category obj, int index) {
        float maxWeight = new Integer(index).floatValue();
        obj.setMaxWeight(maxWeight);
    }
    
    public void CategoryDataOnDemand.setMinWeight(Category obj, int index) {
        float minWeight = new Integer(index).floatValue();
        obj.setMinWeight(minWeight);
    }
    
    public void CategoryDataOnDemand.setName(Category obj, int index) {
        String name = "namexxx_" + index;
        if (name.length() > 17) {
            name = name.substring(0, 17);
        }
        obj.setName(name);
    }
    
    public Category CategoryDataOnDemand.getSpecificCategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Category obj = data.get(index);
        Long id = obj.getId();
        return categoryService.findCategory(id);
    }
    
    public Category CategoryDataOnDemand.getRandomCategory() {
        init();
        Category obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return categoryService.findCategory(id);
    }
    
    public boolean CategoryDataOnDemand.modifyCategory(Category obj) {
        return false;
    }
    
    public void CategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = categoryService.findCategoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Category' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Category>();
        for (int i = 0; i < 10; i++) {
            Category obj = getNewTransientCategory(i);
            try {
                categoryService.saveCategory(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            categoryRepository.flush();
            data.add(obj);
        }
    }
    
}
