// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.ufpb.dsc.mma.domain;

import br.com.ufpb.dsc.mma.domain.FighterIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FighterIntegrationTest_Roo_Configurable {
    
    declare @type: FighterIntegrationTest: @Configurable;
    
}
